### ISSUE TITLE
consider updating requirements.txt to pin ply==3.4

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1014]
We found when deploying m31_001 to findit-test that the latest version of the ply component, 3.6, gets installed; this version of ply outputs the PyZ3950_parsetab.py to directory ENV/lib/python2.7/site-packages/ instead of the launchpad/lp directory

If that's a problem, update the requirements.txt file to specify ply==3.4

**Comment by kerchner** [comment]
Note that there may be value in upgrading to ply 3.6, once we understand what the ply library is used for, and where the PyZ3950_parsetab.py file ought to be placed.

**Comment by dchud** [comment]
In reviewing this, I realized you said "if that's a problem", not "it's a problem." :)  Is this known to cause errors?

**Comment by cummingsm** [comment]
Just that the 3.6-generated file PyZ3950_parsetab.py ends up in a different
directory. I didn't test what will happen if you don't manually copy the
file to the directory launchpad/lp

Thanks,

*Mike *

**Comment by dchud** [comment]
Based on the docs at https://github.com/dabeaz/ply/blob/master/CHANGES#L12 I'm tempted to say -- and also seeing that my dev instance works *after* I've removed the parsetab manually, and it's not regenerated, due to a permissions issue -- that no action is needed here, and ply 3.6 should work.  Let's just keep it in mind during deployment, as something to watch for in case we see errors.
