### ISSUE TITLE
determine best ordering for list of subject headings

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1044]
Sorting the subject headings alphabetically may not be the best approach; when we toggle long lists of headings (issue #1026), are significant headings displayed? 
e.g., search: ocm00373049
e.g., search: 9780803278301

**Comment by lwrubel** [comment]
@cummingsm suggest you take a look at the approach of taking the first three as returned by Summon (seems to match GW's MARC record order) and let's discuss this further. Generally, the top three are decent and better that what gets highlighted in an alpha search. Sometimes however, because of GW's new records, it's a non-English heading. There is nothing in the Summon API response to identify language of the heading, or really, anything else. Sorting by length would not always remove the non-English headings from the top.
