### ISSUE TITLE
identify problem that triggers error as in bib 2690266

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1059]
http://gwdev-cummings.wrlc.org/item/2690266
Traceback (most recent call last):

  File "/launchpad/current/launchpad/lp/ui/views.py", line 72, in item
    holdings = voyager.get_holdings(bib)

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 492, in get_holdings
    holding.update({'MFHD_DATA': get_mfhd_data(holding['MFHD_ID']),

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 792, in get_mfhd_data
    marc856 = get_marc856(string)

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 850, in get_marc856
    if subfield[0] in temp:

IndexError: string index out of range
Request repr() unavailable.

**Comment by lwrubel** [comment]
check voyager.py line 79 and change .get('MARC866', '') to None

**Comment by lwrubel** [comment]
Note: Error seems to actually be with MFHD 14944062 on a WRLC Shared E-Resource record. There are two dollar signs before the 856 subfield u, which is messing up the parsing, and the view in the WRLC record. See from record:

856:40:$zAvailable to ALL WRLC Patrons.$$uhttp://proxywr.wrlc.org/login?url=uhttp://search.ebscohost.com/login.aspx?direct=true&scope=site&db=nlebk&db=nlabk&AN=1185

The data error should be reported to WRLC; however, these records are supposed to be purged from the catalog anyway since the subscription is being turned off in favor of ebrary Academic Complete.

**Comment by cummingsm** [comment]
MFHD 14944062 is associated with WRLC E-Resource bibid 12799910. Submitted WRLC ticket GW-14560 to request correction.

The search for bib 2690266 found a matching  ISBN with bib 12799910.

**Comment by lwrubel** [comment]
Since the data fix worked solved this problem, and the original spot we thought was a problem is actually OK, I'd suggest just closing this. Unless we think this is something that might pop up again, and want to code to handle it.

**Comment by cummingsm** [comment]
Closing ticket. Might also have been resolved by #1098
