### ISSUE TITLE
explore dda print copy request form

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/launchpad#1102]
see #923 for current implementation of print request form. Explore view to provide request form within launchpad.

**Comment by cummingsm** [comment]
Consider displaying the title, ISBN, and any other fields about the title as text on the page rather than a form field -- perhaps in the same format that the item page displays the title, author, ISBN. Those elements can be included in hidden form fields which would be submitted to the google spreadsheet.

Unlike the current Google form, I suggest displaying the email address after the name.

**Comment by lwrubel** [comment]
@cummingsm I have a working form to share with the DDA team to refine the wording. Have not yet made the appearance of the link on the item page conditional on there not being a Request link, so this isn't a pull request yet. 

Note that if you want to look at the work so far, you will need to pip install django-crispy-forms. I'm also adding a setting to settings.py.

**Comment by cummingsm** [comment]
Test case (at least for now) is bibid 15497004. 

Other cases may be found by searching with the 'Online Resource' button checked, with facets selected for  Institution = George Washington University, and Library = GW: Online
